-- =====================================================================
-- Migration 001: Reference tables
-- Scope (STRICT): academic_years, education_levels, management_types,
--                 school_types ONLY.
-- No RLS. No views. No triggers. No functions. No other tables touched.
-- Auth / Storage / connection untouched.
-- =====================================================================

BEGIN;

-- =====================================================================
-- TABLE 1: academic_years
-- Purpose: academic year + general submission calendar.
-- =====================================================================
CREATE TABLE academic_years (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name                TEXT NOT NULL UNIQUE,
    is_active           BOOLEAN NOT NULL DEFAULT false,
    submission_deadline TIMESTAMPTZ NULL
);

-- Integrity: at most ONE active academic year at a time.
-- Enforced via a partial unique index (no trigger/function required).
CREATE UNIQUE INDEX uq_academic_years_single_active
    ON academic_years (is_active)
    WHERE is_active = true;

-- =====================================================================
-- TABLE 2: education_levels
-- Purpose: education levels.
-- =====================================================================
CREATE TABLE education_levels (
    id         SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL UNIQUE,
    sort_order SMALLINT NOT NULL UNIQUE,
    is_active  BOOLEAN NOT NULL DEFAULT true
);

-- =====================================================================
-- TABLE 3: management_types
-- Purpose: school management type.
-- =====================================================================
CREATE TABLE management_types (
    id        SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      TEXT NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT true
);

-- =====================================================================
-- TABLE 4: school_types
-- Purpose: school types bound to an education level.
-- =====================================================================
CREATE TABLE school_types (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    education_level_id SMALLINT NOT NULL
                       REFERENCES education_levels(id) ON DELETE RESTRICT,
    name               TEXT NOT NULL,
    is_active          BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT uq_school_types_level_name UNIQUE (education_level_id, name)
);

-- =====================================================================
-- SEED DATA
-- =====================================================================

-- academic_years: initial active year.
INSERT INTO academic_years (name, is_active, submission_deadline)
VALUES ('2026-2027', true, NULL);

-- education_levels: ordered (id auto-assigned 1..5 by identity).
INSERT INTO education_levels (name, sort_order) VALUES
    ('Okul Öncesi',  1),
    ('İlkokul',      2),
    ('Ortaokul',     3),
    ('Lise',         4),
    ('Özel Eğitim',  5);

-- management_types.
INSERT INTO management_types (name) VALUES
    ('Resmî'),
    ('Özel');

-- school_types: NO seed data here (added later, in a controlled way).

COMMIT;
