-- =====================================================================
-- Migration 002: districts (Adana only)
-- Scope (STRICT): districts table ONLY.
-- First release of PDRPUSULA Risk Map covers ADANA province only,
-- therefore NO provinces table and province info is NOT stored separately.
-- No RLS. No views. No triggers. No functions.
-- Migration 001 tables untouched. Auth / Storage untouched.
-- =====================================================================

BEGIN;

CREATE TABLE districts (
    id        SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      TEXT NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT true
);

-- Seed: Adana districts only.
INSERT INTO districts (name) VALUES
    ('Aladağ'),
    ('Ceyhan'),
    ('Çukurova'),
    ('Feke'),
    ('İmamoğlu'),
    ('Karaisalı'),
    ('Karataş'),
    ('Kozan'),
    ('Pozantı'),
    ('Saimbeyli'),
    ('Sarıçam'),
    ('Seyhan'),
    ('Tufanbeyli'),
    ('Yumurtalık'),
    ('Yüreğir');

COMMIT;
