-- ============================================================
-- Migration 018: Official MEB RİBA Target Seed
-- Kaynak: Resmî MEB RİBA Sınıf Sonuç Çizelgeleri / "madde" sayfası
-- Kademe eşlemesi:
--   1 = Okul Öncesi
--   2 = İlkokul
--   3 = Ortaokul
--   4 = Lise
--
-- Toplam kayıt: 144
-- Okul Öncesi: 27
-- İlkokul: 38
-- Ortaokul: 39
-- Lise: 40
--
-- Bu migration yalnız public.riba_targets tablosunu seed eder.
-- Mevcut bir (education_level_id, meb_code) kaydını overwrite etmez.
-- ============================================================
BEGIN;
INSERT INTO public.riba_targets
    (education_level_id, meb_code, name, is_active)
VALUES
    (1, 'M20', 'İş birliği geliştirme', true),
    (1, 'M11', 'Problem çözme becerileri', true),
    (1, 'M12', 'Yaşam becerileri', true),
    (1, 'M24', 'Otokontrol', true),
    (1, 'M06', 'Öfke yönetimi', true),
    (1, 'M29', 'Okula ve Çevreye Uyum/Okul kuralları', true),
    (1, 'M05', 'Sosyal beceriler', true),
    (1, 'M01', 'Özsaygı geliştirme', true),
    (1, 'M02', 'Özgüven geliştirme', true),
    (1, 'M18', 'Öz disiplin geliştirme', true),
    (1, 'M03', 'Duygu farkındalığı/Duygu düzenleme', true),
    (1, 'M38', 'Yaratıcılık', true),
    (1, 'M36', 'Rehberlik ve Psikolojik Danışma servisinin tanıtılması', true),
    (1, 'M08', 'İletişim becerileri', true),
    (1, 'M07', 'Sosyal beceriler', true),
    (1, 'M09', 'Karar verme becerisi', true),
    (1, 'M35', 'Zaman yönetimi', true),
    (1, 'M27', 'Kariyer gelişimi', true),
    (1, 'M39', 'Yardım arama', true),
    (1, 'M04', 'İletişim becerileri', true),
    (1, 'M10', 'Sınır koyma', true),
    (1, 'M22', 'Bireysel farklılıklara saygı', true),
    (1, 'M13', 'Sağlıklı yaşam', true),
    (1, 'M14', 'İhmal ve istismardan korunma', true),
    (1, 'M34', 'Dikkat geliştirme çalışmaları', true),
    (1, 'M15', 'Bilinçli Teknoloji Kullanımı', true),
    (1, 'M37', 'Okul olgunluğu', true),
    (2, 'M42', 'Özgüven Geliştirme', true),
    (2, 'M28', 'Okula ve Çevreye Uyum/Okul Kuralları', true),
    (2, 'M27', 'Hedef Belirleme', true),
    (2, 'M21', 'Meslek ile İlgi, Değer, Yetenek ve Kişisel Özellik İlişkisi', true),
    (2, 'M40', 'Çatışma Çözme Becerileri', true),
    (2, 'M02', 'Öz Disiplin Geliştirme', true),
    (2, 'M11', 'Karar Verme Becerisi', true),
    (2, 'M14', 'Öz Disiplin Geliştirme', true),
    (2, 'M07', 'Çatışma Çözme Becerileri', true),
    (2, 'M38', 'Aile İçi İletişim', true),
    (2, 'M13', 'Problem Çözme Becerileri', true),
    (2, 'M35', 'Rehberlik ve Psikolojik Danışma Servisinin Tanıtılması', true),
    (2, 'M08', 'Sosyal Beceriler', true),
    (2, 'M16', 'İş Birliği Geliştirme', true),
    (2, 'M19', 'Meslek Tanıtımı', true),
    (2, 'M41', 'Bireysel Farklılıklara Saygı', true),
    (2, 'M15', 'Yaşam Becerileri', true),
    (2, 'M32', 'Dikkat Geliştirme Çalışmaları', true),
    (2, 'M29', 'Öz Düzenlemeli Öğrenme', true),
    (2, 'M31', 'Üst Öğrenim Kurumlarının Tanıtılması', true),
    (2, 'M26', 'Motivasyon/Devamsızlığı Önleme', true),
    (2, 'M04', 'Duygu Farkındalığı/Duygu Düzenleme', true),
    (2, 'M34', 'Okul ve Çevresindeki Sosyokültürel İmkanlar', true),
    (2, 'M12', 'Bilinçli Teknoloji Kullanımı', true),
    (2, 'M05', 'İletişim Becerileri', true),
    (2, 'M06', 'Akran Zorbalığı', true),
    (2, 'M01', 'Hak ve Sorumluluklarını Bilme', true),
    (2, 'M22', 'Meslek ile İlgi, Değer, Yetenek ve Kişisel Özellik İlişkisi', true),
    (2, 'M33', 'Okul ve Çevresindeki Sosyokültürel İmkanlar', true),
    (2, 'M24', 'Verimli Ders Çalışma Teknikleri', true),
    (2, 'M44', 'Sağlıklı Yaşam', true),
    (2, 'M36', 'İhmal ve İstismardan Korunma', true),
    (2, 'M09', 'Sosyal Beceriler', true),
    (2, 'M25', 'Akademik Özyeterlik', true),
    (2, 'M10', 'Sınır Koyma', true),
    (2, 'M18', 'Meslek Sahibi Olmanın Önemi', true),
    (2, 'M30', 'Zaman Yönetimi', true),
    (2, 'M45', 'Yardım Arama', true),
    (3, 'M12', 'Problem Çözme Becerileri', true),
    (3, 'M30', 'Öz Düzenlemeli Öğrenme', true),
    (3, 'M08', 'Karar Verme Becerisi', true),
    (3, 'M29', 'Motivasyon/Devamsızlığı Önleme', true),
    (3, 'M07', 'Sosyal Beceriler', true),
    (3, 'M36', 'Üst Öğrenime Geçiş Sınavları', true),
    (3, 'M34', 'Okul ve Çevresindeki Sosyokültürel İmkanlar', true),
    (3, 'M15', 'Atılganlık', true),
    (3, 'M48', 'Yardım Arama', true),
    (3, 'M04', 'Öz Disiplin Geliştirme', true),
    (3, 'M42', 'Duygu Düzenleme', true),
    (3, 'M11', 'Bilinçli Teknoloji Kullanımı', true),
    (3, 'M31', 'Zaman Yönetimi/Öz Düzenlemeli Öğrenme', true),
    (3, 'M13', 'Gelişim Dönemi Özellikleri', true),
    (3, 'M14', 'Hak ve Sorumluluklarını Bilme', true),
    (3, 'M23', 'Meslek ile İlgi, Değer, Yetenek ve Kişisel Özellik', true),
    (3, 'M32', 'Üst Öğrenim Kurumlarının Tanıtılması', true),
    (3, 'M47', 'Psikolojik Sağlamlık', true),
    (3, 'M33', 'Dikkat Geliştirme Çalışmaları', true),
    (3, 'M16', 'Bağımlılıkla Mücadele', true),
    (3, 'M03', 'İletişim Becerileri', true),
    (3, 'M39', 'Mesleki Benlik', true),
    (3, 'M19', 'Çatışma Çözme Becerileri', true),
    (3, 'M45', 'Bireysel Farklılıklara Saygı', true),
    (3, 'M46', 'Aile İçi İletişim', true),
    (3, 'M06', 'Öfke Yönetimi', true),
    (3, 'M09', 'Sınır Koyma', true),
    (3, 'M27', 'Okula ve Çevreye Uyum/Okul Kuralları', true),
    (3, 'M10', 'İletişim Becerileri', true),
    (3, 'M38', 'Rehberlik ve Psikolojik Danışma Servisinin Tanıtılması', true),
    (3, 'M01', 'Özgüven Geliştirme', true),
    (3, 'M35', 'Okul ve Çevresindeki Sosyokültürel İmkanlar', true),
    (3, 'M22', 'Meslek ile İlgi, Değer, Yetenek ve Kişisel Özellik', true),
    (3, 'M37', 'Sınav Kaygısı', true),
    (3, 'M41', 'İhmal ve İstismardan Korunma', true),
    (3, 'M18', 'Yaşam Becerileri', true),
    (3, 'M44', 'Sağlıklı Yaşam', true),
    (3, 'M05', 'Akran Zorbalığı', true),
    (3, 'M02', 'Duygu Farkındalığı/Duygu Düzenleme', true),
    (4, 'M05', 'Atılganlık', true),
    (4, 'M24', 'Verimli Ders Çalışma Teknikleri/Öz Düzenlemeli Öğrenme', true),
    (4, 'M08', 'Stresle Baş Etme Becerileri', true),
    (4, 'M03', 'Karar Verme Becerisi', true),
    (4, 'M36', 'Psikolojik Sağlamlık', true),
    (4, 'M01', 'Sınır Koyma', true),
    (4, 'M21', 'Meslek ile İlgi, Değer, Yetenek ve Kişisel Özellik İlişkisi', true),
    (4, 'M30', 'Okula ve Çevreye Uyum/Okul kuralları', true),
    (4, 'M09', 'Gelişim Dönemi Özellikleri', true),
    (4, 'M06', 'İletişim Becerileri', true),
    (4, 'M39', 'Otokontrol', true),
    (4, 'M10', 'Gelişim Dönemi Özellikleri', true),
    (4, 'M15', 'İhmal ve İstismardan Korunma', true),
    (4, 'M28', 'Üst Öğrenim Kurumlarının Tanıtılması', true),
    (4, 'M29', 'Üst Öğrenime Geçiş Sınavları', true),
    (4, 'M17', 'Bilinçli Teknoloji Kullanımı', true),
    (4, 'M14', 'İletişim Becerileri', true),
    (4, 'M26', 'Mesleki Hedef Belirleme', true),
    (4, 'M40', 'Aile İçi İletişim', true),
    (4, 'M19', 'Meslek Tanıtımı', true),
    (4, 'M23', 'Meslek Seçerken Dikkat Edilmesi Gereken Hususlar', true),
    (4, 'M42', 'Yardım Arama', true),
    (4, 'M02', 'Öfke Yönetimi', true),
    (4, 'M34', 'Rehberlik ve Psikolojik Danışma Servisinin Tanıtılması', true),
    (4, 'M41', 'Duygu Düzenleme', true),
    (4, 'M13', 'Bağımlılıkla Mücadele', true),
    (4, 'M11', 'Çatışma Çözme Becerileri/Atılganlık', true),
    (4, 'M32', 'Okul ve Çevresindeki Sosyokültürel İmkanlar', true),
    (4, 'M35', 'Sağlıklı Yaşam', true),
    (4, 'M22', 'Meslek ile İlgi, Değer, Yetenek ve Kişisel Özellik İlişkisi', true),
    (4, 'M20', 'Meslek ile İlgi, Değer, Yetenek ve Kişisel Özellik İlişkisi', true),
    (4, 'M37', 'Bireysel Farklılıklara Saygı', true),
    (4, 'M16', 'Bilinçli Teknoloji Kullanımı', true),
    (4, 'M04', 'Özgüven Geliştirme', true),
    (4, 'M25', 'Zaman Yönetimi/ Öz Düzenlemeli Öğrenme', true),
    (4, 'M31', 'Okul ve Çevresindeki Sosyokültürel İmkanlar', true),
    (4, 'M27', 'Sınav Kaygısı', true),
    (4, 'M38', 'Akran Zorbalığı', true),
    (4, 'M43', 'Motivasyon/Devamsızlığı önleme', true),
    (4, 'M44', 'Okulda Seçilecek Alan/Dal', true)
ON CONFLICT (education_level_id, meb_code) DO NOTHING;
COMMIT;
